version: 0.2

phases:
  install:
    commands:
      - npm ci
  pre_build:
    commands:
      - npm test --if-present
  build:
    commands:
      - zip -r artifact.zip . -x "*.git*"
artifacts:
  files:
    - artifact.zip
